text_type_text = "text"
text_type_bold = "bold"
text_type_italic = "italic"
text_type_code = "code"
text_type_link = "link"
text_type_image = "image"

delimiter_code = "`"
delimiter_bold = "**"
delimiter_italics = "*"
delimiter_links = "["
delimiter_image = "!["
delimiter_quotes = ">"

tag_paragraph = ""
tag_heading = "#"
tag_code = "`"
tag_quote = ">"
tag_list = "*"

markdown_paragraph = "paragraph"
markdown_heading = "heading"
markdown_code = "code"
markdown_quote = "quote"
markdown_un_list = "unordered_list"
markdown_ord_list = "ordered_list"